# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edwinchoate.com
email: edwin.choate@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
  Edwin Choate's personal website. Edwin is a current Georgia Tech student
  from Atlanta, GA studying computer science and design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edwinchoate.com" # the base hostname & protocol for your site

# Social media usernames
twitter_username: edwinchoate
github_username:  edwinchoate
instagram_username: edwin.choate
linkedin_username: edwinchoate
soundcloud_username: edwinchoate

# Build settings
markdown: redcarpet

gems:
  - jekyll-redirect-from
